name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 1. 소스 코드를 체크아웃
      - name: Check out code
        uses: actions/checkout@v2

      # 2. JDK 21 설정
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3. gradlew에 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # 4. Gradle을 사용하여 빌드 및 테스트 실행
      - name: Build with Gradle
        run: ./gradlew clean build

      # 5. Docker 로그인 및 이미지 빌드 및 푸시 (main 브랜치에서만 실행)
      - name: Log in to Docker Hub
        if: github.ref == 'refs/heads/main'
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: |
          echo "${{ env.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ env.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        if: github.ref == 'refs/heads/main'
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        run: |
          docker build -t ${{ env.DOCKER_HUB_USERNAME }}/user_service:latest ./user_service
          docker build -t ${{ env.DOCKER_HUB_USERNAME }}/streaming_service:latest ./streaming_service
          docker push ${{ env.DOCKER_HUB_USERNAME }}/user_service:latest
          docker push ${{ env.DOCKER_HUB_USERNAME }}/streaming_service:latest
