name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - dev

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 1. 소스 코드를 체크아웃합니다.
      - name: Check out code
        uses: actions/checkout@v2

      # 2. JDK 21 설정
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3. Gradle을 사용하여 빌드 및 테스트 실행
      - name: Build with Gradle
        run: ./gradlew clean build

      # 4. 테스트가 성공적으로 완료되면 Docker 이미지를 빌드하고 푸시합니다. (main 브랜치에서만 실행)
      - name: Build and push Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker build -t your-dockerhub-username/user_service:latest ./user_service
          docker build -t your-dockerhub-username/streaming_service:latest ./streaming_service
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push your-dockerhub-username/user_service:latest
          docker push your-dockerhub-username/streaming_service:latest
